---
title: "RDM Budget Robustness Initial Analysis"
#author: "Carlos Calvo-Hernandez"
date: "RDM Analysis"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
resource_files:
- 01_setup.R
- 02_growthModel.R
- 03_debtModel.R
---

```{r global, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
files <- list.files(pattern = "^[0-3]{2}(.*).R$")
purrr::map(files, source)

baseGDP <- rep(NA, 76)
baseGDP[1] <- 15000

testMFP <- rep(NA, 76)
testMFP[1] <- 0.0112
baseGrowth <- growthModel(iGDP = as.numeric(baseGDP[1]), dMFP = testMFP, dlTrend = 0.00837, dkTrend = 0.0181) %>% 
  as_tibble()


  for (i in 2:76) {
    baseGDP[i] <- baseGDP[i-1]*(1 + 0.069)
  }

baseDebt <- debtModel(intRate = intRate, intRateTrend = 0.057630, intRateSet = 1, GDP = baseGrowth$GDP) %>% 
  as.tibble()

budgetLines$pol <- policies$Baseline

```

Sidebar {.sidebar}
=======================================================================

### Growth Model Parameters

```{r growth-only}
numericInput("dlTrend", "POPULATION Growth Rate, trend = 0.008370. Range (0.007, 0.01)", value = 0.008370, min = -1, max = 1, step = 0.0005)

numericInput("dkTrend", "CAPITAL Stock Growth Rate, trend = 0.0181. Range (0.01, 0.05)", value = 0.018100, min = -1, max = 1, step = 0.001)

numericInput("dMFP", "PRODUCTIVITY Growth Rate, trend = 0.0112. Range (0.01, 0.02)",  value = 0.011200, min = -1, max = 1, step = 0.001)
```

---
### Budget Model Parameters

```{r debt-only}

numericInput("GDPSet", "Initial Value of GDP", value = 15000, min = 13500, max = 25000, step = 50)

numericInput("GDPGrowth", "GDP Rate of Growth", value = 0.069, min = -1, max = 1, step = 0.001)
# Parameters: intRate, intRateTrend, intRateSet 
numericInput("intRateSet", "Interest Rate set by FIAT (1) or MARKET (0)", value = 1, min = 0, max = 1, step = 1)

numericInput("intRateTrend", "INTEREST RATE on Government Debt, trend = 0.05783. Range (0.025, 0.06)", value = 0.057630, min = -1, max = 1, step = 0.005)

numericInput("intRateIni", "INTEREST RATE, initial (Default 2.7%)", value = 0.027, min = -1, max = 1, step = 0.001)

```

```{r}
selectInput("policy", "Budget Policy", names(policies)[2:7])
reactive({
  print(input$policy)
  print(which(names(policies) == input$policy))
  print(budgetChange()[,1:2])
  print(GDPInput())
  print(debtResultG())
  #print(class(budgetChange()))
  #kableExtra::kbl(budgetChange()$pol)
  })
```

Independent Growth Model and Debt Model
=======================================================================

<!-- Column {.sidebar data-width=300} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### Growth Model Parameters -->

<!-- ```{r growth-only} -->
<!-- numericInput("dlTrendG", "POPULATION Growth Rate, trend = 0.008370. Range (0.007, 0.01)", value = 0.008370, min = -1, max = 1, step = 0.0005) -->

<!-- numericInput("dkTrendG", "CAPITAL Stock Growth Rate, trend = 0.0181. Range (0.01, 0.05)", value = 0.018100, min = -1, max = 1, step = 0.001) -->

<!-- numericInput("dMFP", "PRODUCTIVITY Growth Rate, trend = 0.0112. Range (0.01, 0.02)",  value = 0.011200, min = -1, max = 1, step = 0.001) -->
<!-- ``` -->

<!-- --- -->
<!-- ### Budget Model Parameters -->

<!-- ```{r debt-only} -->

<!-- numericInput("GDPSet", "Initial Value of GDP", value = 15000, min = 13500, max = 25000, step = 50) -->

<!-- numericInput("GDPGrowth", "GDP Rate of Growth", value = 0.069, min = 0.01, max = 0.08, step = 0.001) -->
<!-- # Parameters: intRate, intRateTrend, intRateSet  -->
<!-- numericInput("intRateSetD", "Interest Rate set by FIAT (1) or MARKET (0)", value = 1, min = 0, max = 1, step = 1) -->

<!-- numericInput("intRateTrendD", "INTEREST RATE on Government Debt, trend", value = 0.057630, min = 0.0250, max = 0.06, step = 0.005) -->

<!-- numericInput("intRateIniD", "INTEREST RATE, initial (Default 2.7%)", value = 0.027, min = 0.02, max = 0.05, step = 0.001) -->

<!-- ``` -->


Column {data-width=700}
-----------------------------------------------------------------------

### Growth Model Results

```{r}
growthResG <- reactive({ 
  dMFPparm <- rep(NA, 76)
  dMFPparm[1] <- input$dMFP
  modelRes <- as_tibble(growthModel(iGDP = input$GDPSet, dlTrend = input$dlTrend, dkTrend = input$dkTrend, dMFP = dMFPparm))
  return(modelRes)
})
#coeff <- sqrt(sum(growthRes$GDP^2))

renderPlot({ 
  gdp_pg <- ggplot(data = growthRes(), aes(x = 1:76))+
  geom_line(aes(y = GDP), size = 1.1, color = "purple")+
  geom_line(data = baseGrowth, aes(y = GDP), color = "black", alpha = 0.5)+
  # geom_line(aes(y = MFP*coeff)) +
   scale_y_continuous(name = "GDP", labels = scales::label_dollar(), breaks = scales::breaks_extended(n=4))+
    xlab("Time")+
    ggtitle("GDP over time", subtitle = "Black line = Baseline")
  #                    sec.axis = sec_axis(~./coeff, name =  "MFP"))
  #plotly::ggplotly(p, tooltip = c('y', 'x'))
  
  mfp_pg <- ggplot(data = growthRes(), aes(x = 1:76))+
  geom_line(aes(y = MFP), size = 1.1, color = "purple")+
  geom_line(data = baseGrowth, aes(y = MFP), color = "black", alpha = 0.5)+
  # geom_line(aes(y = MFP*coeff)) +
   scale_y_continuous(name = "MFP")+
    xlab("Time")+
    ggtitle("MFP over time")
  
  cowplot::plot_grid(gdp_pg, mfp_pg, labels = "AUTO")
  
})
```

### Budget Model Results

```{r}
GDPInput <- reactive({
  GDP <- rep(NA, 76)
  GDP[1] <- input$GDPSet
  for (i in 2:76) {
    GDP[i] <- GDP[i-1]*(1 + input$GDPGrowth)
  }
  return(GDP)
})

debtResultG <- reactive({ 
  intRate <- rep(NA, 76)
  intRate[1] <- input$intRateIni
  as_tibble(debtModel(intRate = intRate, intRateTrend = input$intRateTrend, intRateSet = input$intRateSet, GDP = GDPInput()))
  })

renderPlot({
  debt_p <- ggplot(data = debtResult(), aes(x = 1:76))+
  geom_line(aes(y = Debt), size = 1.1, color = "purple")+
    geom_point(aes(y = Debt), size = 1.1, color = "black")+
  geom_line(data = baseDebt, aes(y = Debt), color = "black", alpha = 0.5)+
  # geom_line(aes(y = MFP*coeff)) +
   scale_y_continuous(name = "Debt", labels = scales::label_dollar())+
    xlab("Time")+
    ggtitle("Debt over time")
  
  df <- tibble(growth = GDPInput(), time = (1:76))
  gdp <- ggplot(data = df, aes(x = (1:76), y = growth))+
    geom_line(color = "purple")+
    scale_y_continuous(name = "GDP", labels = scales::label_dollar())+
    xlab("Time")+
    ggtitle("GDP over time")
  
  cowplot::plot_grid(debt_p, gdp, labels = "AUTO")
})
```


Growth-dependent Debt Model
=======================================================================

<!-- Column {.sidebar data-width=300} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### Budget Growth Parameters -->

<!-- ```{r growth} -->
<!-- numericInput("dlTrend", "POPULATION Growth Rate, Trend = 0.00837. Range (0.007, 0.01)", value = 0.008370, min = -1, max = 1, step = 0.0005) -->

<!-- numericInput("dkTrend", "CAPITAL Stock Growth Rate, Trend = 0.018100. Range (0.01, 0.05)", value = 0.018100, min = -1, max = 1, step = 0.001) -->

<!-- numericInput("dMFP", "PRODUCTIVITY Growth Rate, Trend = 0.011200. Range (0.01, 0.02)", value = 0.011200, min = -1, max = 1, step = 0.001) -->
<!-- ``` -->
<!-- --- -->
<!-- ### Debt Growth Parameters -->

<!-- ```{r debt} -->
<!-- # Parameters: intRate, intRateTrend, intRateSet  -->
<!-- numericInput("intRateSet", "Interest Rate set by FIAT (1) or MARKET (0)", value = 1, min = 0, max = 1, step = 1) -->

<!-- numericInput("intRateTrend", "INTEREST RATE on Government Debt, trend = 0.05783. Range (0.025, 0.06)", value = 0.057630, min = -1, max = 1, step = 0.005) -->

<!-- numericInput("intRateIni", "INTEREST RATE, initial (Default 2.7%)", value = 0.027, min = -1, max = 1, step = 0.001) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- selectInput("policy", "Budget Policy", names(policies)[2:7]) -->
<!-- reactive({ -->
<!--   print(input$policy) -->
<!--   print(which(names(policies) == input$policy)) -->
<!--   print(budgetChange()[,1:2]) -->
<!--   #print(class(budgetChange())) -->
<!--   #kableExtra::kbl(budgetChange()$pol) -->
<!--   }) -->
<!-- ``` -->


Column {data-width=700}
-----------------------------------------------------------------------

### Growth Model Results

```{r}
growthRes <- reactive({ 
  withProgress(message = "Calculating GDP", value = 0, {
    incProgress()
    dMFPparm <- rep(NA, 76)
  dMFPparm[1] <- input$dMFP
  modelRes <- as_tibble(growthModel(iGDP = input$GDPSet, dlTrend = input$dlTrend, dkTrend = input$dkTrend, dMFP = dMFPparm))
  return(modelRes)  
  })
})
#coeff <- sqrt(sum(growthRes$GDP^2))

renderPlot({ 
  gdp_p <- ggplot(data = growthRes(), aes(x = 1:76))+
  geom_line(aes(y = GDP), size = 1.1, color = "purple")+
  # geom_line(aes(y = MFP*coeff)) +
   scale_y_continuous(name = "GDP", labels = scales::label_dollar(), breaks = scales::breaks_extended(n=4))+
    xlab("Time")+
    ggtitle("GDP over time", subtitle = "$ in thousands")
  #                    sec.axis = sec_axis(~./coeff, name =  "MFP"))
  #plotly::ggplotly(p, tooltip = c('y', 'x'))
  
  mfp_p <- ggplot(data = growthRes(), aes(x = 1:76))+
  geom_line(aes(y = MFP), size = 1.1, color = "purple")+
  # geom_line(aes(y = MFP*coeff)) +
   scale_y_continuous(name = "MFP")+
    xlab("Time")+
    ggtitle("MFP over time")
  
  cowplot::plot_grid(gdp_p, mfp_p, labels = "AUTO")

  
})
```

### Budget Model Results

```{r}
#browser()
budgetChange <- reactive({
  changes <- policies[which(names(policies) == input$policy)]
  polChange <- budgetLines %>% 
    mutate(pol = deframe(changes))
  
})
 
debtResult <- reactive({ 
  intRate <- rep(NA, 76)
  intRate[1] <- input$intRateIni
  change <- policies[which(names(policies) == input$policy)]
  budgetLines$pol <- deframe(change)
  # budgetLines <- budgetLines %>%  
  #   mutate(pol = deframe(change))
  #print(budgetLines)
  as_tibble(debtModel(intRate = intRate, intRateTrend = input$intRateTrend, intRateSet = input$intRateSet, GDP = growthRes()$GDP, budgetData = budgetChange()))
  })


renderPlot({
  debt_p <- ggplot(data = debtResult(), aes(x = 1:76))+
  geom_line(aes(y = Debt), size = 1.1, color = "purple")+
    geom_point(aes(y = Debt), size = 1.1, color = "black")+
  # geom_line(aes(y = MFP*coeff)) +
   scale_y_continuous(name = "Debt", labels = scales::label_dollar())+
    xlab("Time")+
    ggtitle("Debt over time")
  
  budget_p <- ggplot(data = debtResult(), aes(x = 1:76))+
    geom_line(aes(y = Balance, color = "Balance"))+
    geom_line(aes(y = ExpendituresAgg, color = "Expenditures"))+
    geom_line(aes(y = TaxAgg, color = "Revenue"))+
    scale_y_continuous(name = "$", labels = scales::label_dollar(), breaks = scales::breaks_extended(n=4))+
    xlab("Time")+
    ggtitle("Expenditure, Revenue, and Balance")+
    scale_color_manual(name = "Variable", labels = c("Balance", "Expenditures", "Revenue"), values = c("blue", "red", "green"))+
    theme(legend.position = "right")
    
  
  cowplot::plot_grid(debt_p, budget_p, labels = "AUTO")
})
```


Integrated Growth and Debt Model
=======================================================================

Column {data-width=700}
-----------------------------------------------------------------------

### Growth Model Results




### Budget Model Resultss

